/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zigolive_wrappers_K8061Wrapper */

#ifndef _Included_com_zigolive_wrappers_K8061Wrapper
#define _Included_com_zigolive_wrappers_K8061Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    OpenDevice
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zigolive_wrappers_K8061Wrapper_OpenDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    CloseDevices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_CloseDevices
  (JNIEnv *, jobject);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    PowerGood
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zigolive_wrappers_K8061Wrapper_PowerGood
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    Connected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zigolive_wrappers_K8061Wrapper_Connected
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ReadVersion
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ReadVersion
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ReadAnalogChannel
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ReadAnalogChannel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ReadAllAnalog
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ReadAllAnalog
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    OutputAnalogChannel
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_OutputAnalogChannel
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    OutputAllAnalog
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_OutputAllAnalog
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ClearAnalogChannel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ClearAnalogChannel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ClearAllAnalog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ClearAllAnalog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    SetAnalogChannel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_SetAnalogChannel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    SetAllAnalog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_SetAllAnalog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    OutputPWM
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_OutputPWM
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    OutputAllDigital
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_OutputAllDigital
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ClearDigitalChannel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ClearDigitalChannel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ClearAllDigital
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ClearAllDigital
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    SetDigitalChannel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_SetDigitalChannel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    SetAllDigital
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zigolive_wrappers_K8061Wrapper_SetAllDigital
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ReadDigitalChannel
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ReadDigitalChannel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zigolive_wrappers_K8061Wrapper
 * Method:    ReadAllDigital
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zigolive_wrappers_K8061Wrapper_ReadAllDigital
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
